import type { Section } from './types';

/** Binds "where in the world / when in the scroll" to "what the resume says." Editing the journey
 * timing touches this file; editing the actual words touches resume.ts; neither touches scene code. */
export const SECTIONS: Section[] = [
  {
    id: 'approach',
    region: 'approach',
    dataRef: 'profile',
    heading: 'Welcome',
    start: -0.02,
    end: 0.09,
    fadeIn: 0.04,
    fadeOut: 0.04,
  },
  {
    id: 'about',
    region: 'about',
    dataRef: 'about',
    heading: 'About Me',
    start: 0.05,
    end: 0.27,
    fadeIn: 0.05,
    fadeOut: 0.05,
  },
  {
    id: 'experience',
    region: 'north',
    dataRef: 'experience',
    heading: 'Work Experience',
    start: 0.2,
    end: 0.47,
    fadeIn: 0.06,
    fadeOut: 0.06,
  },
  {
    id: 'projects',
    region: 'war',
    dataRef: 'projects',
    heading: 'Projects',
    start: 0.4,
    end: 0.66,
    fadeIn: 0.06,
    fadeOut: 0.06,
  },
  {
    id: 'paper',
    region: 'archive',
    dataRef: 'paper',
    heading: 'Research',
    start: 0.59,
    end: 0.79,
    fadeIn: 0.05,
    fadeOut: 0.05,
  },
  {
    id: 'education',
    region: 'education',
    dataRef: 'education',
    heading: 'Education',
    start: 0.73,
    end: 0.87,
    fadeIn: 0.04,
    fadeOut: 0.04,
  },
  {
    id: 'contact',
    region: 'parley',
    dataRef: 'contact',
    heading: 'Contact',
    start: 0.83,
    end: 1.02,
    fadeIn: 0.05,
    fadeOut: 0.05,
  },
];
