import type { Section } from './types';

/** Binds "where in the world / when in the scroll" to "what the resume says," plus the
 * chronicler's one-line voice-over for that chapter. Editing the journey timing touches
 * this file; editing the actual words touches resume.ts; neither touches scene code. */
export const SECTIONS: Section[] = [
  {
    id: 'approach',
    region: 'approach',
    dataRef: 'profile',
    heading: 'THE APPROACH',
    start: -0.02,
    end: 0.09,
    fadeIn: 0.04,
    fadeOut: 0.04,
    labelText: 'The North Road',
    voiceLine: 'Some men measure their worth in ledgers. In the North, you measure it in the ground you’ve crossed.',
  },
  {
    id: 'about',
    region: 'about',
    dataRef: 'about',
    heading: 'THE CHRONICLER',
    start: 0.05,
    end: 0.27,
    fadeIn: 0.05,
    fadeOut: 0.05,
    labelText: 'A Traveler’s Account',
    voiceLine: 'I’ve walked with soldiers, scholars, and worse. This is the account of one more traveler worth knowing.',
  },
  {
    id: 'experience',
    region: 'north',
    dataRef: 'experience',
    heading: 'THE NORTH',
    start: 0.2,
    end: 0.47,
    fadeIn: 0.06,
    fadeOut: 0.06,
    labelText: 'The North',
    voiceLine: 'Every campaign leaves a mark on the man who marched it. Here are his.',
  },
  {
    id: 'projects',
    region: 'war',
    dataRef: 'projects',
    heading: 'THE WAR',
    start: 0.4,
    end: 0.66,
    fadeIn: 0.06,
    fadeOut: 0.06,
    labelText: 'The Fields of War',
    voiceLine: 'A campaign is remembered by what it built, not just what it won.',
  },
  {
    id: 'education',
    region: 'education',
    dataRef: 'education',
    heading: 'THE CIRCLE OF THE WORLD',
    start: 0.59,
    end: 0.79,
    fadeIn: 0.05,
    fadeOut: 0.05,
    labelText: 'The Circle of the World',
    voiceLine: 'Before the sword, the trial. Before the trial, the teacher.',
  },
  {
    id: 'paper',
    region: 'archive',
    dataRef: 'paper',
    heading: 'THE ARCHIVE',
    start: 0.73,
    end: 0.87,
    fadeIn: 0.04,
    fadeOut: 0.04,
    labelText: 'The Sealed Archive',
    voiceLine: 'Some victories are won with steel. Some are sealed in ink and left for others to find.',
  },
  {
    id: 'contact',
    region: 'parley',
    dataRef: 'contact',
    heading: 'THE PARLEY',
    start: 0.83,
    end: 1.02,
    fadeIn: 0.05,
    fadeOut: 0.05,
    labelText: 'The Parley',
    voiceLine: 'Every journey ends at a table where terms are offered. Here are mine.',
  },
];
